name: Docker Image

on:
  push:
  workflow_dispatch:

jobs:
  ghcr:
    name: ${{ github.ref == 'refs/heads/main' && 'Build and Push' || 'Test Build' }}
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Login to ghcr.io
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: ${{ github.ref == 'refs/heads/main' && 'Build and Push' || 'Test Build' }}
        uses: docker/build-push-action@15560696de535e4014efeff63c48f16952e52dd1 # v6
        with:
            push: ${{ github.ref == 'refs/heads/main' }}
            tags: ghcr.io/countr/countr:latest
